name: Remove test-triggering label

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  remove-label:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Remove PR label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              var fs = require('fs');
              var issue_number = Number(fs.readFileSync('./NR'));
              console.log("PR: " + issue_number");
              await github.rest.issues.removeLabel({
                name: 'tests: run',
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number
              });
            } catch (e) {
              console.log('No such label.');
            }
